"""add deleted to menu

Revision ID: 07d88f8e4647
Revises: 1f2593f8c3b2
Create Date: 2023-08-12 09:49:08.240602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d88f8e4647'
down_revision = '1f2593f8c3b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'deleted')
    # ### end Alembic commands ###
