"""add soft-delete to menu-item & -section

Revision ID: 1f2593f8c3b2
Revises: 126e97867dd9
Create Date: 2023-08-11 19:05:24.770926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2593f8c3b2'
down_revision = '126e97867dd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('menu_sections', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_sections', 'deleted')
    op.drop_column('menu_items', 'deleted')
    # ### end Alembic commands ###
