"""add price to menu item

Revision ID: 22d8570d9241
Revises: 064db566f0e4
Create Date: 2023-08-03 12:14:39.109524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d8570d9241'
down_revision = '064db566f0e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'price')
    # ### end Alembic commands ###
