"""rename menu title to restaurant

Revision ID: 688a09176d29
Revises: aa931fd332e2
Create Date: 2023-08-01 20:04:11.260306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688a09176d29'
down_revision = 'aa931fd332e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('restaurant', sa.String(length=100), nullable=True))
    op.drop_column('menus', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('menus', 'restaurant')
    # ### end Alembic commands ###
