"""add closed to meal

Revision ID: aa816ace99b0
Revises: fd517a50c180
Create Date: 2023-08-05 08:47:15.729774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa816ace99b0'
down_revision = 'fd517a50c180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('closed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'closed')
    # ### end Alembic commands ###
