"""add title to menu and owner to meal

Revision ID: aa931fd332e2
Revises: 4f4a38d0e42b
Create Date: 2023-08-01 13:18:11.852151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa931fd332e2'
down_revision = '4f4a38d0e42b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.alter_column('meals', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'meals', 'users', ['owner_id'], ['id'])
    op.add_column('menus', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'title')
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.alter_column('meals', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('meals', 'owner_id')
    # ### end Alembic commands ###
