"""Add name to menu section

Revision ID: e33447b14a56
Revises: 688a09176d29
Create Date: 2023-08-02 09:45:02.215269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33447b14a56'
down_revision = '688a09176d29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_sections', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_sections', 'name')
    # ### end Alembic commands ###
