"""add menu to meal

Revision ID: fd517a50c180
Revises: 22d8570d9241
Create Date: 2023-08-03 16:22:23.085985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd517a50c180'
down_revision = '22d8570d9241'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('menu_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'meals', 'menus', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.drop_column('meals', 'menu_id')
    # ### end Alembic commands ###
